// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkxydgbmsvsqxsienncu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndreHlkZ2Jtc3ZzcXhzaWVubmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNDYxNjYsImV4cCI6MjA1OTgyMjE2Nn0.sHgZniEvu8-lq0qSevVU59bIqviYI6fX8i36YpC1ESg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);